### ISSUE TITLE
A couple of implementation questions

### ISSUE THREAD

**Issue by izaskr** [aeye-lab/etra-reading-comprehension#18]
Hi,

I got your code running and have a couple of questions regarding the implementation:

1. When defining the embedding layer of PoSNet, you use vocabulary size of 2 (line [here](https://github.com/aeye-lab/etra-reading-comprehension/blob/803b9d69108f9f296d0bf2c9b92aebfaff733db7/nn/model.py#L47)), but there are 3 simplified POS-tags: FUNC, N and A.
2. The GSFNet subnetwork processes feature vectors of dimensionality 634. The paper explains the value as 35 x 18 + 4 = 634. I guess 18 comes from 5 (linguistic features) + 13 (reading measures), while 4 is a vector (total number of words, total number of fixations, stationary gaze entropy, gaze transition entropy). But where does 35 come from?
3. In the code, the SB-SAT dataset is first preprocessed with a separate command. When running the training, the dataset is further preprocessed. Do you by chance have the data from this step saved into files?

Thank you for the help!

**Comment by SiQube** [comment]
Hi, 

very cool that it is working! :) Thanks for being the first publicly testing person outside our lab! :) Thanks also for your patients, we tried it here but not clean enough :-)

I'll answer your questions 1-by-1 below:

1. When defining the embedding layer of PoSNet, you use vocabulary size of 2 (line [here](https://github.com/aeye-lab/etra-reading-comprehension/blob/803b9d69108f9f296d0bf2c9b92aebfaff733db7/nn/model.py#L47)), but there are 3 simplified POS-tags: FUNC, N and A.

I don't really know how you come to a vocabulary size of two, we are defining it [here](https://github.com/aeye-lab/etra-reading-comprehension/blob/803b9d69108f9f296d0bf2c9b92aebfaff733db7/nn/model.py#L426), and account for the possibility of `len(pos-tag-list) + 1` (+1 for unknowns).

2. The GSFNet subnetwork processes feature vectors of dimensionality 634. The paper explains the value as 35 x 18 + 4 = 634. I guess 18 comes from 5 (linguistic features) + 13 (reading measures), while 4 is a vector (total number of words, total number of fixations, stationary gaze entropy, gaze transition entropy). But where does 35 come from?


$$ \left|\text{PoS-tags}\right| \times F_\text{aggregated}+ \left|\text{Simplified PoS-tags}\right| \times F_\text{aggregated} + \left|\text{Content Word}\right| \times F_\text{aggregated} +  \left|\text{Named Entity Type}\right| \times F_\text{aggregated}$$

$$= 16 \times 18 + 5 \times 18 + 3\times 18 + 11 \times 18=35\times 18,$$

where $F_\text{aggregated}$ is the number (18) of aggregated features. Additionally, like you already said, we added the four features you described in your question. So we aggregated each of the different word categories and take into account the number of fixations on each word.

4. In the code, the SB-SAT dataset is first preprocessed with a separate command. When running the training, the dataset is further preprocessed. Do you by chance have the data from this step saved into files?

Yes, we have but didn't publish it because you can generate it with the scripts in the git. I can share them with you somehow if you write me an [e-mail](david.reich@uni-potsdam.de). Would also love to chat about what you are working on.

Thanks again for the interest in our research and looking forward to hearing from you.
